### ISSUE TITLE
请问一下安装module报错的问题原因

### ISSUE THREAD

**Issue by thurendous** [twtrubiks/odoo-demo-addons-tutorial#1]
demo_expense_tutorial_v1模块我安装的时候，好像是以下的相关文件报错。请问是什么原因呢？如何解决？
demo_expense_tutorial_v1/security/ir.model.access.csv

![image](https://user-images.githubusercontent.com/40059593/99770238-df5e3700-2b4a-11eb-9371-3b6de6da792f.png)

**Comment by thurendous** [comment]
发现错误了，好像是init文件没导入models，文件复制时候好像报了一个疑问我点错了，抱歉

**Comment by thurendous** [comment]
啊 不对，还是报错。。不知道怎么问题
![image](https://user-images.githubusercontent.com/40059593/99773942-81345280-2b50-11eb-9ad6-eefc5d99fcab.png)

**Comment by thurendous** [comment]
![image](https://user-images.githubusercontent.com/40059593/99774341-01f34e80-2b51-11eb-871c-d6dbeba428a1.png)
更改了导入的顺序在manifest中，之后报了别的错误。我是odoo13的版本，
![image](https://user-images.githubusercontent.com/40059593/99774650-70d0a780-2b51-11eb-8d62-48b8028c8a01.png)

**Comment by twtrubiks** [comment]
@thurendous  Hi  謝謝你的提醒,
我剛剛測試了一下, 只要把 menu.xml 和 view.xml 順序掉換過來就可以了  [56c0812](https://github.com/twtrubiks/odoo-demo-addons-tutorial/commit/56c08126d04bdae59309405def3bd86520333e44)  (我在 odoo12 上重新測試過了),
如果還是有問題請再回報, 謝謝.
這是我一直新增教學導致沒注意到的 bug .

我也有提供 odoo14 版本的, 請參考 [14.0-demo_expense_tutorial_v1](https://github.com/twtrubiks/odoo-demo-addons-tutorial/tree/14.0/demo_expense_tutorial_v1)

**Comment by thurendous** [comment]
好的 谢谢！我再试试
