### ISSUE TITLE
如何强制运行fields_view_get方法

### ISSUE THREAD

**Issue by fanlitcn** [twtrubiks/odoo-demo-addons-tutorial#2]
如何强制运行fields_view_get方法， 因为这个方法只有在刷新页面时才执行， 有没有什么方法可以让他按要求运行

**Comment by twtrubiks** [comment]
@fanlitcn  暫時沒有, 因為這似乎是它的機制.  不然就是要去研究更底層的 code.

**Comment by fanlitcn** [comment]
好的, 谢谢你的分享, 学到好多东西, 谢谢
