### ISSUE TITLE
有没有介绍前端widget，owl的。

### ISSUE THREAD

**Issue by jackadam1981** [twtrubiks/odoo-demo-addons-tutorial#3]
最近的需求大概是图片存储分离，用sftp，nginx分布访问。
这就要改前端了，做个widget是比较方便使用的。
你有这方面的研究么？

**Comment by twtrubiks** [comment]
@jackadam1981 我主要是寫後端的, OWL這部份沒有研究.
或許可考慮 NFS ? 不確定這是不是你要的,
我看 odoo store 有人把他存到 s3上, 但是要付費的 addons,
或許你可以買來參考看看.

**Comment by jackadam1981** [comment]
http://mixoo.cn/2017/08/29/odoo-customize-fields/
有他的笔记，但是看不懂。

**Comment by twtrubiks** [comment]
@jackadam1981 我看了一下, 雖然他是舊版的, 但算是蠻清楚的, 剩下就是想辦法把他實作到你現在的 odoo 版本.

**Comment by jackadam1981** [comment]
水平有限，看不懂，慢慢修炼，反正刚开始，数据量也不大，即使存在应用服务器，数据库也无所谓。
或许16，改owl以后，前端又有大的改动。先实现业务流程吧，实在搞不定，就加硬件，钱能解决的问题，也就不是问题了。
:)
本来考虑的是一台服务器做odoo应用，一台服务器做数据库，一台服务器做存储。
技术水平有限，搞不定。

**Comment by jackadam1981** [comment]
https://github.com/oca/storage
https://github.com/camptocamp/odoo-cloud-platform/
这两个库也非常有参考价值，但是也是看不懂。
JS就没学会。
widget的渲染模板，也没搞懂。

**Comment by twtrubiks** [comment]
@jackadam1981  感謝分享
我的看法和你一樣, 我覺得初期的確不用一開始就切開, 先能用在說XD

另外我測了一下  https://github.com/OCA/storage/tree/14.0/storage_backend_sftp
感覺依賴蠻多的, 我再找些時間研究一下
