### ISSUE TITLE
odoo-bin 指令更新 addons 失败?

### ISSUE THREAD

**Issue by ZoomQuiet** [twtrubiks/odoo-demo-addons-tutorial#4]
从视频 [(1) odoo 教學 - 使用 CLI 安裝, 更新 addons - YouTube](https://www.youtube.com/watch?v=k19N2x8f4gw&list=PLteWjpkbvj7pbdPXhIqgtX3v3pQxHz-5l&index=26) 追踪过来;

为了合理化开发路径, 是这么配置项目的:
```
/opt/src/
  +- odoo/   <-- Odoo15 源代码
  |  +- addons/
  |  +- ...
  +- ostock/ <-- 开发入口
  |  +- addons/
  |   |  +- demo_controller_api_http/
  |  +- ...
  ...
```

> 根据提示, 进行指令更新 addons 时, 尝试这样来:

/opt/src/ostack/addons$ python3 ../../odoo/odoo-bin -u demo_controller_api_http -d odoo150

但是, 出现 ERROE:

```
...
2022-07-07 15:23:11,529 8625 ERROR odoo150 odoo.modules.loading: Some modules are not loaded, some dependencies or manifest may be missing: ['rowno_in_tree'] 
2022-07-07 15:23:11,826 8625 ERROR odoo150 odoo.modules.loading: Some modules have inconsistent states, some dependencies may be missing: ['demo_controller_api_http'] 
```
并且一直没有完成更新并退出;

当然, 对应配置中有多目录指向:

`addons_path =/opt/src/odoo/addons,/opt/src/ostack/addons`

所以, 请教:

- 快速更新 addons 时, odoo 本身应该停止嘛? 按照以往网页上操作, 并不用专门停止的?
- 用 odd-bin 指令更新时, 必须带上启动 odoo 时对应的 -c 配置嘛?

PS:
使用 systemctl 来控制 odoo 的启动,
对应 odoo15.service 如下:
```
[Unit]
Description=Odoo15
Requires=postgresql.service
After=network.target postgresql.service

[Service]
Type=simple
SyslogIdentifier=odoo15
PermissionsStartOnly=true
User=zoomq
Group=zoomq
ExecStart=/opt/src/odoo/.py380/bin/python3 /opt/src/odoo/odoo-bin -w Pa55w02d! -r odoo -c /opt/src/ostack/config/odoo15.conf
StandardOutput=journal+console

[Install]
WantedBy=multi-user.target

```

**Comment by twtrubiks** [comment]
@ZoomQuiet 
出现 ERROE 的原因
-> 看起來你沒有加上你的 `-c`  odoo.conf, 所以它不知道你的 addons 在哪裡.

快速更新 addons 时, odoo 本身应该停止嘛? 按照以往网页上操作, 并不用专门停止的?
-> 快速更新 addons, odoo本身是不會停止的,
如果你想要測試 addons, 應該使用 `--stop-after-init` 這個參數.
這個參數執行完會停止.

用 odd-bin 指令更新时, 必须带上启动 odoo 时对应的 -c 配置嘛?
-> 當然要帶上你的 `-c` 對應你的 conf, 不然就是全都補上 terminal 上面(但我覺得這樣很醜)

**Comment by ZoomQuiet** [comment]
@twtrubiks 果然, 尝试后理解了指令 -u 的实际行为

要和 .service 或是 .vscode/lunch.js 中配置的完全一致,
也就是说, 在调试过程中, 就是用 odoo-bin 本身来启动整个儿 Odoo 环境, 只是通过参数来快速完成开发中 addons 的更新

比如, 俺的本地环境

要先用 
$ sudo systemctl stop odoo15
停止 odoo 环境

然后, 在在开发目录中使用
/opt/src/ostack/addons$
/opt/src/odoo/.py380/bin/python3 /opt/src/odoo/odoo-bin -u demo_controller_api_http -w Pa55w02d! -r odoo -c /opt/src/ostack/config/odoo15.conf

就完成了:
1: addons 更新
2: odoo 启动

当然, 开始守护服务, 不会退出, 所以, 日常应该是:

$ sudo systemctl stop odoo15
$ /opt/src/odoo/.py380/bin/python3 /opt/src/odoo/odoo-bin -u demo_controller_api_http -w Pa55w02d! -r odoo -c /opt/src/ostack/config/odoo15.conf --stop-after-init
$ sudo systemctl start odoo15

三个指令循环来完成 addons 的指令更新, 来替代界面上的点点点...

当然, 要是在个人开发, 没有其它人使用时, 始终开个终端, 一直用标准指令来启动 odoo 并更新也可以:

$ /opt/src/odoo/.py380/bin/python3 /opt/src/odoo/odoo-bin -u demo_controller_api_http -w Pa55w02d! -r odoo -c /opt/src/ostack/config/odoo15.conf 

以上?
