### ISSUE TITLE
當你更新 One2many 和 Many2many 時, 要使用比較特別的語言,我之後會補充上來.

### ISSUE THREAD

**Issue by jackadam1981** [twtrubiks/odoo-demo-addons-tutorial#5]
當你更新 One2many 和 Many2many 時, 要使用比較特別的語言,我之後會補充上來.

用到了，还没更新。

**Comment by jackadam1981** [comment]
多对多关系的删除。

**Comment by twtrubiks** [comment]
請參考 [odoo 手把手教學 - 使用 python 增加取代 One2many M2X record - part8](https://github.com/twtrubiks/odoo-demo-addons-tutorial/tree/master/demo_expense_tutorial_v1#odoo-%E6%89%8B%E6%8A%8A%E6%89%8B%E6%95%99%E5%AD%B8---%E4%BD%BF%E7%94%A8-python-%E5%A2%9E%E5%8A%A0%E5%8F%96%E4%BB%A3-one2many-m2x-record---part8)

以及 [這篇底下的](https://github.com/twtrubiks/odoo-demo-addons-tutorial/tree/master/demo_odoo_tutorial#%E4%BB%8B%E7%B4%B9-security-menu-tree-form)
```text
(0, _ , {'field': value}) creates a new record and links it to this one.
(1, id, {'field': value}) updates the values on an already linked record.
(2, id, _) removes the link to and deletes the id related record.
(3, id, _) removes the link to, but does not delete, the id related record. This is usually what you will use to delete related records on many-to-many fields.
(4, id, _) links an already existing record.
(5, _, _) removes all the links, without deleting the linked records.
(6, _, [ids]) replaces the list of linked records with the provided list.
```

**Comment by jackadam1981** [comment]
谢谢
