### ISSUE TITLE
Odoo15 的 sudo() 不支持 user 切换?

### ISSUE THREAD

**Issue by ZoomQuiet** [twtrubiks/odoo-demo-addons-tutorial#7]
>>> self.env['hr.expense'].sudo().search([])
hr.expense(6, 5, 4, 3, 2, 1)
>>> self.env['hr.expense'].sudo(user=11).search([])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: sudo() got an unexpected keyword argument 'user'

**Comment by twtrubiks** [comment]
@ZoomQuiet  其實我的文章有說明, 下面是文章片段

注意 :exclamation: 這是 odoo12 的作法,

從 odoo13 開始切換 user 已經改成 `with_user(user)` :exclamation: 可參考 [odoo13-souece code](https://github.com/odoo/odoo/blob/13.0/odoo/models.py#L5160)

`deprecated use of sudo(user), use with_user(user) instead`

**Comment by ZoomQuiet** [comment]
@twtrubiks 囧...
还是要认真查阅,
多谢指引.
