### ISSUE TITLE
odoo 15 本地运行报“Error: QWeb2: Can't clone undefined template ListView.buttons”的错误

### ISSUE THREAD

**Issue by gongmin00** [twtrubiks/odoo-demo-addons-tutorial#8]
hello你好 我想搭建odoo本地的开发环境。然后我需要把线上的环境搭建到本地，所以我在线上
1. 导出了dump.sql 和filestore文件，
2. 本地根据yaml文件配置 在docker container里面运行起一个空的db数据库
3. 然后再通过docker exec命令 把sql文件导入本地db数据库里面，
4. 并且把线上filestore文件覆盖本地的data_dir
5. 然后根据odoo.confi文件跑起来odoo.
感觉数据库没问题，可以正常进入http://localhost:8088/web/database/manager 页面，但是登录进web前端页面的时候就会报错

Uncaught (in promise) Error: QWeb2: Can't clone undefined template ListView.buttons
    at Object.exception (web.assets_common.min.js:4451:7)
    at Engine.add_template (web.assets_common.min.js:4467:361)
    at web.assets_common.min.js:4926:6

![Screen Shot 2024-05-21 at 3 49 20 PM](https://github.com/twtrubiks/odoo-demo-addons-tutorial/assets/50763352/de581b9c-32e9-4067-8c62-8563d2b3c8d6)

这里是我的odoo.yaml文件配置
![Screen Shot 2024-05-21 at 4 04 43 PM](https://github.com/twtrubiks/odoo-demo-addons-tutorial/assets/50763352/52356756-be2b-4ec9-8427-07177ea3fa80)

这个是odoo.conf文件配置
![Screen Shot 2024-05-21 at 4 04 10 PM](https://github.com/twtrubiks/odoo-demo-addons-tutorial/assets/50763352/362a8f49-c2f7-4fc7-9580-a89214621a34)

**Comment by twtrubiks** [comment]
@gongmin00  你的需求是一定要還原 dump 嘛？  因為只還原 dump 非常容易出問題, 你的 zip 是非常大嘛？
如果 zip 可以備份, 建議用 zip 備份. 但如果 zip 檔案大於 2g, 就建議用 dump 還原.

**Comment by gongmin00** [comment]
> @gongmin00 你的需求是一定要還原 dump 嘛？ 因為只還原 dump 非常容易出問題, 你的 zip 是非常大嘛？ 如果 zip 可以備份, 建議用 zip 備份. 但如果 zip 檔案大於 2g, 就建議用 dump 還原.

是的，因为里面存的数据比较大，所以才用dump还原。 
我已经figure out了， 用odoo cli命令 -u <modules> 命令 来 重新reload一遍web组件就解决了。
感谢您的回复
